"use client";

import React, { useState, useRef } from "react";
import { ChevronDown, HelpCircle } from "lucide-react";
import gsap from "gsap";
import { ScrollTrigger } from "gsap/ScrollTrigger";
import { useGSAP } from "@gsap/react";

if (typeof window !== "undefined") {
  gsap.registerPlugin(ScrollTrigger);
}

export default function FAQAccordion() {
  const containerRef = useRef<HTMLElement>(null);
  const faqs = [
    {
      q: "What is Ownix real estate ownership?",
      a: "Ownix ownership allows multiple investors to collectively own a property by purchasing smaller investment units.",
    },
    {
      q: "How do I earn returns?",
      a: "Returns can come through rental income generated by the property and long-term appreciation in property value.",
    },
    {
      q: "Can I invest with a small amount?",
      a: "Yes. The platform is designed to help retail investors start with lower investment amounts compared to traditional property purchases.",
    },
    {
      q: "Who manages the property?",
      a: "The platform and associated management teams handle operational and management aspects of the property.",
    },
    {
      q: "Is Ownix ownership legal in India?",
      a: "Ownix ownership structures operate through legally compliant investment and ownership models.",
    },
    {
      q: "Can I invest in more than one property?",
      a: "Yes. Investors can diversify by investing in multiple properties across different categories and locations.",
    },
  ];

  const [openIndex, setOpenIndex] = useState<number | null>(0); // Default open first item mimicking the reference state

  const toggleFaq = (index: number) => {
    setOpenIndex(openIndex === index ? null : index);
  };

  useGSAP(() => {
    if (!containerRef.current) return;

    gsap.fromTo(
      ".gsap-faq-header",
      { opacity: 0, x: -30 },
      {
        opacity: 1,
        x: 0,
        duration: 0.8,
        ease: "power3.out",
        scrollTrigger: {
          trigger: containerRef.current,
          start: "top 80%",
          toggleActions: "play none none none",
        },
      }
    );

    gsap.fromTo(
      ".gsap-faq-list",
      { opacity: 0, y: 30 },
      {
        opacity: 1,
        y: 0,
        duration: 0.8,
        ease: "power3.out",
        scrollTrigger: {
          trigger: containerRef.current,
          start: "top 80%",
          toggleActions: "play none none none",
        },
      }
    );
  }, { scope: containerRef });

  return (
    <section id="faqs" ref={containerRef} className="py-20 sm:py-32 bg-white relative overflow-hidden border-b border-slate-100 opacity-99">
      
      <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8">
        
        {/* Asymmetric Reference Layout Grid */}
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-10 lg:gap-16 items-start">
          
          {/* Left Column: Reference-Grade Pill Tag & Split Typography */}
          <div className="lg:col-span-5 lg:sticky lg:top-32 pt-2 gsap-faq-header">
            
            {/* Soft accent pill tag mimicking reference layout verbatim */}
            <div className="inline-flex items-center gap-2 px-3.5 py-1.5 rounded-full bg-emerald-50 text-xs font-medium text-emerald-700 mb-5 border border-emerald-100/50">
              <HelpCircle className="w-3.5 h-3.5 text-emerald-600 shrink-0" />
              <span>Frequently asked questions</span>
            </div>

            {/* Verbatim Section Heading formatted for optimal two-color visual break */}
            <h2 className="text-4xl sm:text-5xl lg:text-6xl font-bold tracking-tight text-slate-900 leading-[1.08]">
              Frequently asked <br />
              <span className="text-emerald-600 font-medium">questions</span>
            </h2>

          </div>


          {/* Right Column: Stacked Rounded Box Panels matching the mock */}
          <div className="lg:col-span-7 gsap-faq-list">
            <div className="space-y-4">
              {faqs.map((faq, idx) => {
                const isOpen = openIndex === idx;
                return (
                  <div
                    key={idx}
                    id={`faq-item-${idx}`}
                    className={`rounded-[20px] transition-all duration-300 overflow-hidden ${
                      isOpen
                        ? "bg-[#f8f9fa] shadow-2xs"
                        : "bg-[#f8f9fa] hover:bg-[#f1f3f5]"
                    }`}
                  >
                    <button
                      id={`faq-trigger-${idx}`}
                      onClick={() => toggleFaq(idx)}
                      className="w-full text-left py-5 pl-6 pr-5 flex items-center justify-between gap-4 focus:outline-none group"
                      aria-expanded={isOpen}
                    >
                      <span className="text-base sm:text-lg font-semibold text-slate-900 group-hover:text-emerald-700 transition-colors duration-200">
                        {faq.q}
                      </span>
                      
                      {/* Integrated circular Chevron Module mimicking the reference mock exactly */}
                      <div
                        className={`w-8 h-8 rounded-full flex items-center justify-center shrink-0 transition-all duration-300 ${
                          isOpen
                            ? "bg-emerald-600 text-white shadow-2xs"
                            : "bg-emerald-100/80 text-emerald-700 group-hover:bg-emerald-200/80"
                        }`}
                      >
                        <ChevronDown
                          className={`w-4 h-4 stroke-[2.5] transition-transform duration-300 ${
                            isOpen ? "rotate-180" : "rotate-0"
                          }`}
                        />
                      </div>
                    </button>
                    {/* Silky-Smooth Grid-Template-Rows Expandable Answer Reveal */}
                    <div
                      className={`grid transition-all duration-300 ease-in-out ${
                        isOpen ? "grid-rows-[1fr] opacity-100" : "grid-rows-[0fr] opacity-0"
                      }`}
                    >
                      <div className="overflow-hidden">
                        <div
                          id={`faq-answer-${idx}`}
                          className="pb-6 pl-6 pr-10 text-sm sm:text-base text-slate-500 leading-relaxed font-normal"
                        >
                          <p>{faq.a}</p>
                        </div>
                      </div>
                    </div>
                  </div>
                );
              })}
            </div>
          </div>

        </div>

      </div>
    </section>
  );
}
