"use client";

import React, { useState } from "react";
import { ChevronDown, HelpCircle } from "lucide-react";

export default function FAQAccordion() {
  const faqs = [
    {
      q: "What is Ownix real estate ownership?",
      a: "Ownix ownership allows multiple investors to collectively own a property by purchasing smaller investment units.",
    },
    {
      q: "How do I earn returns?",
      a: "Returns can come through rental income generated by the property and long-term appreciation in property value.",
    },
    {
      q: "Can I invest with a small amount?",
      a: "Yes. The platform is designed to help retail investors start with lower investment amounts compared to traditional property purchases.",
    },
    {
      q: "Who manages the property?",
      a: "The platform and associated management teams handle operational and management aspects of the property.",
    },
    {
      q: "Is Ownix ownership legal in India?",
      a: "Ownix ownership structures operate through legally compliant investment and ownership models.",
    },
    {
      q: "Can I invest in more than one property?",
      a: "Yes. Investors can diversify by investing in multiple properties across different categories and locations.",
    },
  ];

  const [openIndex, setOpenIndex] = useState<number | null>(0); // Default open first FAQ

  const toggleFaq = (index: number) => {
    setOpenIndex(openIndex === index ? null : index);
  };

  return (
    <section id="faqs" className="py-24 bg-white border-b border-slate-100 relative">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
        
        {/* Title Header */}
        <div className="text-center max-w-2xl mx-auto mb-16">
          <div className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-emerald-50 border border-emerald-100 text-xs font-bold uppercase tracking-widest text-emerald-800 mb-3 font-mono shadow-2xs">
            <HelpCircle className="w-3.5 h-3.5" />
            <span>Support Center</span>
          </div>
          <h2 className="text-3xl sm:text-4xl font-extrabold text-slate-900 tracking-tight">
            Frequently Asked Questions
          </h2>
          <p className="text-slate-600 text-sm mt-2">
            Clear, transparent answers directly from our asset structured models.
          </p>
        </div>

        {/* Accordion Panel List */}
        <div className="space-y-4">
          {faqs.map((faq, idx) => {
            const isOpen = openIndex === idx;
            return (
              <div
                key={idx}
                id={`faq-container-${idx}`}
                className={`rounded-2xl border transition-all duration-300 overflow-hidden ${
                  isOpen
                    ? "bg-white border-emerald-600 shadow-md"
                    : "bg-slate-50 border-slate-200 hover:border-slate-300 shadow-2xs"
                }`}
              >
                <button
                  id={`faq-trigger-${idx}`}
                  onClick={() => toggleFaq(idx)}
                  className="w-full text-left px-6 py-5 flex items-center justify-between gap-4 focus:outline-none group"
                  aria-expanded={isOpen}
                >
                  <span className="text-base font-bold text-slate-900 group-hover:text-emerald-700 transition-colors duration-200">
                    {faq.q}
                  </span>
                  <div
                    className={`p-1 rounded-lg transition-transform duration-300 shrink-0 ${
                      isOpen ? "bg-emerald-600 text-white rotate-180" : "bg-white text-slate-500 border border-slate-200"
                    }`}
                  >
                    <ChevronDown className="w-4 h-4" />
                  </div>
                </button>

                {isOpen && (
                  <div
                    id={`faq-answer-${idx}`}
                    className="px-6 pb-5 pt-1 text-sm text-slate-600 leading-relaxed border-t border-slate-100 animate-in fade-in duration-200"
                  >
                    <p>{faq.a}</p>
                  </div>
                )}
              </div>
            );
          })}
        </div>

        {/* Support Note */}
        <div className="mt-12 text-center bg-slate-50 p-4 rounded-xl border border-slate-200 max-w-md mx-auto text-xs text-slate-600 shadow-2xs">
          Have an unlisted query? Email advisory desks at{" "}
          <a href="mailto:info@thegoldtechnologies.com" className="text-emerald-700 font-bold hover:underline">
            info@thegoldtechnologies.com
          </a>
        </div>

      </div>
    </section>
  );
}
